### ISSUE TITLE
Замечания по lw0 (1)

### ISSUE THREAD

**Issue by lulldev** [Rabbit864/Clock#1]
Привести код в соответствии с https://github.com/lulldev/webdev/tree/master/coding-convections

**Comment by lulldev** [comment]
```js
let clock = document.getElementById("clock");

function changeTime(){
	let time = new Date().toLocaleTimeString();
	clock.textContent = time;
}

setInterval(changeTime,1000);

```

вызов старта интервала и доступа к элементу DOM ` document.getElementById("clock")` поместить в событии onload (window.onload)

**Comment by Rabbit864** [comment]
Исправленно

**Comment by lulldev** [comment]
https://github.com/Rabbit864/Clock/blob/master/css/main.css

скобка не должна прилипать к классу/id 
https://github.com/lulldev/webdev/blob/master/coding-convections/css-style.md

**Comment by Rabbit864** [comment]
Исправил
